<?php

namespace App\Services;

use App\Models\Attachment;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Http\UploadedFile;
use Illuminate\Support\Facades\Storage;

/**
 * Stores uploaded files on the private disk and records them as attachments.
 *
 * Two rules matter here: the stored filename is always generated by Laravel
 * (never derived from user input), and the original name is kept as metadata
 * only. Nothing is written to a publicly served path.
 */
class AttachmentService
{
    public function storeFor(Model $attachable, UploadedFile $file, ?int $uploadedBy = null, string $collection = 'default'): ?Attachment
    {
        $disk = config('daruso.uploads.disk');

        $path = $file->store("{$collection}/{$attachable->getMorphClass()}", $disk);

        if ($path === false) {
            return null;
        }

        return $attachable->attachments()->create([
            'disk' => $disk,
            'file_path' => $path,
            'file_name' => $file->getClientOriginalName(),
            'file_mime_type' => $file->getClientMimeType(),
            'file_size' => $file->getSize() ?: 0,
            'collection' => $collection,
            'uploaded_by' => $uploadedBy,
        ]);
    }

    /**
     * Replace the file on an existing attachment, removing the old file.
     */
    public function replace(Attachment $attachment, UploadedFile $file, ?int $uploadedBy = null): Attachment
    {
        $oldPath = $attachment->file_path;

        $attachment->update([
            'file_path' => $file->store("{$attachment->collection}/{$attachment->attachable_type}", $attachment->disk),
            'file_name' => $file->getClientOriginalName(),
            'file_mime_type' => $file->getClientMimeType(),
            'file_size' => $file->getSize() ?: 0,
            'uploaded_by' => $uploadedBy,
        ]);

        if ($oldPath !== $attachment->file_path) {
            Storage::disk($attachment->disk)->delete($oldPath);
        }

        return $attachment;
    }

    public function delete(Attachment $attachment): void
    {
        Storage::disk($attachment->disk)->delete($attachment->file_path);
        $attachment->delete();
    }
}
